spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password:  123456
    username:  root
    url: jdbc:mysql://49.233.196.4:3306/weather?autoReconnect=true&useUnicode=true&characterEncoding=utf8&testOnBorrow=true&serverTimezone=UTC

server:
  port: 8990
